### PR TITLE
Allows --fix option

### PR DESCRIPTION
**Pull request by katerberg**

### CODE REVIEW

**Comment by IanVS** [comment]
Interesting.  I'm curious what the use case would be for using this option during tests.  It seems like you wouldn't usually want your test suite to be making changes to the code, because those changes are not going to be committed, and could cause the tests to pass even though the commit itself is failing.

**Comment by katerberg** [comment]
We tend to keep our unit tests running while developing using `--watch`. Because we don't want to pollute our webpack with test files, we rely on mocha-eslint to handle catching and fixing issues in the tests while running them. I agree that `--fix` would not be helpful as part of a push gateway or on a CI server, but while running locally, it is invaluable.

Let me know if I can help clarify any other way!

**Comment by IanVS** [comment]
Thanks for explaining.  I'm still thinking this over and trying to decide if it's a good idea to add it.  It's not a use case I've considered much before.  I would feel a little better if we did a check for a `CI` environment variable and disabled fixing if it's found (although that's not foolproof, it adds a small measure of safety).  What do you think about that idea?

**Comment by katerberg** [comment]
Oh, right now it's set as an optional parameter that you can pass. If you don't set anything it does not use `--fix` but if you pass `fix: true`, it does. I wouldn't want to force the change on everyone which is why it's implemented as an opt-in choice.

**Comment by IanVS** [comment]
@katerberg I understand, but I worry that users would enable it without thinking of the implications for CI, where their tests would pass but the committed code could be broken.  This is why I consider it to be a somewhat dangerous option.  

There have also been thoughts of allowing arbitrary eslint options.  https://github.com/BadgeLabs/mocha-eslint/pull/50 is one such attempt.  I think if we did something like this, we wouldn't need a separate `fix` option like you have here, right?

**Comment by katerberg** [comment]
For most parameters, we wouldn't need a separate flag, but for `--fix` we still would because it requires an output: `CLIEngine.outputFixes(report);`

I can see the worry about people accidentally turning on the fix flag, but generally it seems like people rarely toggle on parameters unless they have a reason. If it required user action to disable, then I think it would be a big concern, but as an opt-in flag, it seems relatively innocuous.

**Comment by katerberg** [comment]
Closing since it sounds like it's not in the plan for this project.

**Pull request closed without merging**
