### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ratson**

### CODE REVIEW

**Comment by ratson** [comment]
@IanVS Any chance this being merged and published?

**Comment by IanVS** [comment]
Sure. Could you update the Travis config to run against node 6, 8, and 10? Thanks for the PR.

**Comment by ratson** [comment]
@IanVS Cherry picked https://github.com/BadgeLabs/mocha-eslint/pull/60 to this PR.

**Comment by IanVS** [comment]
Published as `5.0.0`.  Thanks @ratson.

**Pull request merged**
