### PR TITLE
Ignore tests in npm

### PR DESCRIPTION
**Pull request by knownasilya**
See https://github.com/ember-cli/ember-cli/issues/6147 for context

### CODE REVIEW

**Comment by IanVS** [comment]
👍  Thanks.

**Comment by IanVS** [comment]
Released in [v3.0.1](https://github.com/BadgeLabs/mocha-eslint/releases/tag/v3.0.1)

**Comment by knownasilya** [comment]
Sweet

**Comment by Turbo87** [comment]
@IanVS this PR is somewhat redundant as https://github.com/BadgeLabs/mocha-eslint/blob/master/package.json#L34-L36 exists already and does the same thing

**Comment by IanVS** [comment]
Doh, you're totally right.  I forgot I had that there.  Oh well, at least it doesn't hurt anything.

I'm guessing this package shows up as being so large on ember-cli/ember-cli#6147 is because it's pulling in ESLint.

**Comment by knownasilya** [comment]
Ah, forgot about that option..

**Pull request merged**
