### PR TITLE
 add Node v4 to travis

### PR DESCRIPTION
**Pull request by eagleeye**
Also, it would be good if you publish a new minor version of this package

### CODE REVIEW

**Comment by IanVS** [comment]
A bump isn't necessary, due to the `^`.  The other changes look good though.  Don't need to release a new minor version, as there is no functional changes since the last version.

**Comment by eagleeye** [comment]
@IanVS yea, true. I was sure, that mocha-eslint will not install eslint 1.5, but i just checked that you are right). I've removed unneeded bump

**Comment by IanVS** [comment]
Thanks, can you please squash commits, and I will merge.

**Comment by eagleeye** [comment]
@IanVS done

**Comment by IanVS** [comment]
Thanks!

**Pull request merged**
